services:
  msc-postgres:
    image: postgres:16-alpine
    container_name: msc-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: msc_user
      POSTGRES_PASSWORD: msc_password
      POSTGRES_DB: msc_db
    ports:
      - '5432:5432'
    volumes:
      - msc_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U msc_user -d msc_db']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  msc_postgres_data:
