model_list:
  - model_name: vertex-gemini-pro
    litellm_params:
      model: vertex_ai/gemini-3.1-pro-preview
      vertex_project: "wordpress-map-1492461083797"
      vertex_location: "global"
      vertex_credentials: "D:/Antigravity_Projectz/Node-Launcher/gcp_key.json"

  - model_name: vertex-gemini-flash
    litellm_params:
      model: vertex_ai/gemini-3-flash-preview
      vertex_project: "wordpress-map-1492461083797"
      vertex_location: "global"
      vertex_credentials: "D:/Antigravity_Projectz/Node-Launcher/gcp_key.json"

litellm_settings:
  drop_params: true
  set_verbose: false
