#!/usr/bin/env node
/**
 * MSC design asset ingestion — strip foreign utilities, apply msc-import-* namespace
 * Usage: npm run msc:ingest -- <input.html> <output-dir>
 * Powered by the MSC Media Engine
 */
import './lib/msc-load-env.mjs';
import './lib/msc-node-version-guard.mjs';

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { MSC_PROJECT_ROOT } from './lib/msc-load-env.mjs';

const [, , inputPath, outputDirArg] = process.argv;

if (!inputPath || !outputDirArg) {
  console.error('Usage: npm run msc:ingest -- <input.html> <output-dir>');
  process.exit(1);
}

const inputAbs = join(MSC_PROJECT_ROOT, inputPath);
const outputDir = join(MSC_PROJECT_ROOT, outputDirArg);

/** Common Tailwind / foreign utility tokens to strip */
const TAILWIND_UTILITIES = new Set([
  'flex',
  'grid',
  'block',
  'inline',
  'inline-flex',
  'hidden',
  'p-0',
  'p-1',
  'p-2',
  'p-3',
  'p-4',
  'p-5',
  'p-6',
  'p-8',
  'px-4',
  'py-2',
  'py-4',
  'm-0',
  'm-4',
  'mx-auto',
  'my-4',
  'text-white',
  'text-black',
  'text-gray-900',
  'text-2xl',
  'text-xl',
  'text-lg',
  'text-sm',
  'text-xs',
  'font-bold',
  'font-semibold',
  'font-medium',
  'bg-gray-900',
  'bg-white',
  'bg-black',
  'rounded',
  'rounded-lg',
  'shadow',
  'shadow-lg',
  'w-full',
  'h-full',
  'items-center',
  'justify-center',
  'gap-2',
  'gap-4',
]);

function stripScripts(html) {
  return html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, '');
}

function stripInlineStyles(html) {
  return html.replace(/\sstyle="[^"]*"/gi, '').replace(/\sstyle='[^']*'/gi, '');
}

function rewriteClasses(html) {
  return html.replace(/\bclass="([^"]*)"/gi, (_match, classValue) => {
    const tokens = classValue
      .split(/\s+/)
      .filter(Boolean)
      .filter((t) => !TAILWIND_UTILITIES.has(t))
      .map((t) => (t.startsWith('msc-import-') ? t : `msc-import-${t.replace(/^msc-/, '')}`));
    if (tokens.length === 0) return '';
    return ` class="${tokens.join(' ')}"`;
  });
}

function wrapShieldRoot(html) {
  const bodyMatch = html.match(/<body[^>]*>([\s\S]*?)<\/body>/i);
  const inner = bodyMatch ? bodyMatch[1].trim() : html.trim();
  const wrapped = `<motion.div class="msc-viewport-shield msc-shield-root">\n${inner}\n</motion.div>`;
  if (bodyMatch) {
    return html.replace(/<body[^>]*>[\s\S]*?<\/body>/i, `<body>\n${wrapped}\n</body>`);
  }
  return wrapped;
}

const raw = readFileSync(inputAbs, 'utf8');
let processed = stripScripts(raw);
processed = stripInlineStyles(processed);
processed = rewriteClasses(processed);
processed = wrapShieldRoot(processed);

const timestamp = Date.now();
const baseName = `msc-import-${timestamp}`;
const htmlOut = join(outputDir, `${baseName}.html`);
const cssOut = join(outputDir, `${baseName}.css`);

const companionCss = `/**
 * MSC ingest companion — Studio Dark tokens only (var(--msc-*))
 * Generated by msc-ingest.mjs
 */
.msc-import-btn-primary {
  background-color: var(--msc-accent);
  color: var(--msc-text-primary);
  border: none;
  border-radius: var(--msc-radius);
  padding: var(--msc-gap-sm) var(--msc-gap-md);
  cursor: pointer;
  transition: var(--msc-transition);
}

.msc-import-btn-primary:hover {
  background-color: var(--msc-accent-hover);
}

.msc-import-hero {
  background-color: var(--msc-bg-surface);
  color: var(--msc-text-primary);
  padding: var(--msc-gap-lg);
}
`;

mkdirSync(outputDir, { recursive: true });
writeFileSync(htmlOut, processed, 'utf8');
writeFileSync(cssOut, companionCss, 'utf8');

console.log(
  `[msc:ingest] Wrote ${htmlOut.replace(`${MSC_PROJECT_ROOT}/`, '').replace(/\\/g, '/')}`,
);
console.log(`[msc:ingest] Wrote ${cssOut.replace(`${MSC_PROJECT_ROOT}/`, '').replace(/\\/g, '/')}`);
